### ISSUE TITLE
抓取数据失败了

### ISSUE THREAD

**Issue by HamGuy** [threegirl2014/RenRenDownload#3]
/home/vagrant/Code/webBlog/local/lib/python2.7/site-packages/bs4/**init**.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 54 of the file Main.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
get all album list
all album save successfully, time: 0:00:00.000023
2016-09-02 05:08:23.212222 : status save successfully
2016-09-02 05:08:23.350145 : bloglist save successfully
Traceback (most recent call last):
  File "Main.py", line 54, in <module>
    Main()
  File "Main.py", line 43, in Main
    bloglist.work()
  File "/home/vagrant/Code/RenRenDownload/src/BlogList.py", line 83, in work
    self.saveEveryBlog()
  File "/home/vagrant/Code/RenRenDownload/src/BlogList.py", line 71, in saveEveryBlog
    blog.work()
  File "/home/vagrant/Code/RenRenDownload/src/Blog.py", line 39, in work
    self.saveBlog()
  File "/home/vagrant/Code/RenRenDownload/src/Blog.py", line 23, in saveBlog
    with open(self.filename, 'w+') as f:
IOError: [Errno 71] Protocol error: u'data/232306894/blogs/2008-09-18 21:41:45  \u9ed8\u8ba4\u5206\u7c7b  \u8001\u4e61\u7684\u7f51\u7ad9.markdown'

**Comment by threegirl2014** [comment]
环境问题吧，看看和这个一样不一样http://stackoverflow.com/questions/24640819/protocol-error-setting-up-virtualenvironment-through-vagrant-on-ubuntu
