### ISSUE TITLE
No module named MySQLdb

### ISSUE THREAD

**Issue by rainssong** [threegirl2014/RenRenDownload#4]
Traceback (most recent call last):
  File "Main.py", line 15, in <module>
    from RepoMysql import RepoMysql
  File "/Volumes/D/Users/Rain/Downloads/RenRenDownload-master/RenRenDownload-master/src/RepoMysql.py", line 6, in <module>
    import MySQLdb
ImportError: No module named MySQLdb

必须安装mysql？

**Comment by threegirl2014** [comment]
@rainssong 是的，你看requirements.txt
